CREATE TABLE `demo_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`full_name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`company` varchar(255),
	`industry` varchar(100),
	`calls_per_month` int,
	`preferred_date_time` timestamp,
	`additional_message` text,
	`ip_address` varchar(45),
	`user_agent` text,
	`referrer` text,
	`utm_source` varchar(255),
	`utm_medium` varchar(255),
	`utm_campaign` varchar(255),
	`session_id` varchar(255),
	`time_on_page` int,
	`form_completion_time` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `demo_bookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partner_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`full_name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`company` varchar(255) NOT NULL,
	`partner_type` enum('reseller','integrator','consultant','agency') NOT NULL,
	`ai_voip_experience` text,
	`target_market` text,
	`potential_clients` int,
	`estimated_monthly_budget` int,
	`portfolio_document` text,
	`status` enum('pending','approved','rejected','negotiating') NOT NULL DEFAULT 'pending',
	`review_notes` text,
	`reviewed_at` timestamp,
	`reviewed_by` int,
	`ip_address` varchar(45),
	`user_agent` text,
	`referrer` text,
	`utm_source` varchar(255),
	`utm_medium` varchar(255),
	`utm_campaign` varchar(255),
	`session_id` varchar(255),
	`time_on_page` int,
	`form_completion_time` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partner_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `roi_calculations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`full_name` varchar(255),
	`company` varchar(255),
	`industry` varchar(100) NOT NULL,
	`calls_per_month` int NOT NULL,
	`current_response_rate` int NOT NULL,
	`avg_client_value` int NOT NULL,
	`confirmation_rate` int,
	`missed_calls_per_month` int,
	`lost_revenue_per_month` int,
	`lost_revenue_per_year` int,
	`current_receptionist_cost` int,
	`klarson_cost_per_year` int,
	`total_savings_per_year` int,
	`roi_percentage` int,
	`payback_days` int,
	`ip_address` varchar(45),
	`user_agent` text,
	`referrer` text,
	`utm_source` varchar(255),
	`utm_medium` varchar(255),
	`utm_campaign` varchar(255),
	`session_id` varchar(255),
	`time_on_page` int,
	`form_completion_time` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `roi_calculations_id` PRIMARY KEY(`id`)
);
