CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title_en` varchar(255) NOT NULL,
	`title_es` varchar(255) NOT NULL,
	`title_ro` varchar(255) NOT NULL,
	`excerpt_en` text NOT NULL,
	`excerpt_es` text NOT NULL,
	`excerpt_ro` text NOT NULL,
	`content_en` text NOT NULL,
	`content_es` text NOT NULL,
	`content_ro` text NOT NULL,
	`category` enum('case-study','ai-insights','how-to-guide') NOT NULL,
	`author` varchar(255) NOT NULL,
	`author_role` varchar(255),
	`cover_image` text,
	`reading_time` int,
	`meta_description_en` text,
	`meta_description_es` text,
	`meta_description_ro` text,
	`meta_keywords` text,
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`published_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
